### ISSUE TITLE
feat(settings): add System Info tool

### ISSUE THREAD

**Issue by mathetos** [impress-org/wp-business-reviews#170]
As a WPBR user, whenever I have technical issues, I want to be able to provide Support with actionable information about my WordPress environment.

I expect there to be a basic System Info tool to provide that easily with just copy/paste.

I'd recommend it be in one of these two places:
1. Somewhere on the Help tab seems to be most obvious, but that's already a very full space.
2. It would fit very easily on the Advanced tab, but it's not a natural place to look for something like that.

**Comment by kevinwhoffman** [comment]
I think a `System Info` tab after the `Help` tab would be cleanest and most obvious.

**Comment by kevinwhoffman** [comment]
**Slack Call Summary**
Participants: @mathetos @kevinwhoffman
Topic: Adding Sytem Info to WPBR
Result: We are hoping to add System Info in a way that can eventually be incorporated into the WordPress Core system info which is planned to merge in 5.0. Keep an eye on this Trac ticket: https://core.trac.wordpress.org/ticket/39165

**Comment by kevinwhoffman** [comment]
Closing in favor of #285.
