### ISSUE TITLE
fix: use the WordPress date format in reviews

### ISSUE THREAD

**Issue by kevinwhoffman** [impress-org/wp-business-reviews#240]
## User Story

As an international user, I want the date format to reflect my WordPress date settings so that the dates displayed in reviews are clear to visitors in my locale.

## Acceptance Criteria

- [x] Dates appearing in reviews on the front end are formatted according to WordPress date settings.
- [x] Dates appearing throughout WP admin are formatted according to WordPress date settings.
    - [x] Single reviews
    - [x] Single review editor

**Comment by mathetos** [comment]
Customer reported this issue here:
https://secure.helpscout.net/conversation/651002928/24263/

**Comment by marutim** [comment]
Another user asking for this: https://secure.helpscout.net/conversation/730774148/0/?folderId=2120001

**Comment by marutim** [comment]
Another HS ticket on this: https://secure.helpscout.net/conversation/758330796/32906?folderId=2120001

**Comment by marutim** [comment]
Here is another request for this: https://secure.helpscout.net/conversation/761290805/33134/
