### ISSUE TITLE
fix: ensure Facebook reviewer image URLs do not expire

### ISSUE THREAD

**Issue by marutim** [impress-org/wp-business-reviews#261]
## Current Behavior

When I try and "get reviews" the profile pictures appear in the collection in the backend but once I save the reviews, most of the profile pictures disappear.

Check the screenshots for more details.

## Expected Behavior
I am not sure if this is due to a change in the API, otherwise, the name and profile picture in the reviews should display correctly.

## Steps to Reproduce
1. Create an FB reviews collection. You will see the profile pictures when the reviews are fetched.
2. Once you have hit the save button, most the profile pictures will disappear.
3. Now view the collection in the front end to see the missing profile picture and linkless profile name.

## Visuals
![1](https://user-images.githubusercontent.com/3498917/45547541-bb9e5880-b83e-11e8-9550-e95b4376d91b.png)
![2](https://user-images.githubusercontent.com/3498917/45547543-bd681c00-b83e-11e8-8aee-c4cbc18c500c.png)
![3](https://user-images.githubusercontent.com/3498917/45547547-bfca7600-b83e-11e8-9e79-4bae1fd5d53d.png)

## Related
HS link: https://secure.helpscout.net/conversation/662286842/25392?folderId=2231395

## Acceptance Criteria
- [x] FB reviews display the profile pictures when first retrieved over API.
- [x] FB reviews display the profile pictures after saving.
- [x] FB reviews are stored as the 302 redirect format to ensure they do not expire in the future.

**Comment by kevinwhoffman** [comment]
## Slack Chat Summary

**Participants:** @marutim @kevinwhoffman
**Topic:** Missing Facebook images
**Result:** Kevin has seen the missing images happen before temporarily. In the past it has resolved itself with no changes on our end. It seems to be a hiccup in the Facebook Graph API. We have not seen a user report it yet. Maruti will follow up on Monday to see if it's still an issue.

**Comment by kevinwhoffman** [comment]
I have seen the missing images behavior again and I understand why now. The endpoint used to retrieve the images returns URLs that expire, at which point the reviewer images are no longer accessible. Need to investigate whether there is a way around this expiration.

https://developers.facebook.com/docs/graph-api/reference/user/picture/

**Comment by kevinwhoffman** [comment]
Here is the new URL structure to use for reviewer images which will always retrieve the user's current profile picture: https://developers.facebook.com/docs/graph-api/reference/user/picture/
