### ISSUE TITLE
fix: settings page fatal error

### ISSUE THREAD

**Issue by marutim** [impress-org/wp-business-reviews#280]
# Bug Report
## User Story

As a user, I would like to be able to use/access the Settings submenu. Now I can not access it due to a fatal error. I can access all other submenus

I created a new local website to test this and could replicate the error while adding a new API in the settings page. 
You can check this video for details: https://www.useloom.com/share/06727e81f1ac498a8feeb1210ed60fda

## Current Behavior

Settings submenu is inaccessible due to a fatal error

## Expected Behavior

Settings Submenu should be accessible for old and new setup

## Bug Type

- [ ] This bug describes functionality that once worked as expected in the previous version or infact I remember it working for the same version.

## Steps to Reproduce
- Create a new WP setup
- Download the latest version ( 1.1).  I downloaded it from my account in https://wpbusinessreviews.com/
- Install and activate the plugin.
- Go to Reviews >> Settings >> Platforms >> Select the platforms and save changes
- Now select a platform to enter the API key ( I tested with Google ) and save changes to see the error

## Visuals
![image](https://user-images.githubusercontent.com/3498917/48197292-5ae15700-e37b-11e8-8c16-014c2cb2a3df.png)
![image](https://user-images.githubusercontent.com/3498917/48197317-6cc2fa00-e37b-11e8-86f5-4f6a877f1069.png)
![settings wpbr test wordpress](https://user-images.githubusercontent.com/3498917/48197434-bb709400-e37b-11e8-90c5-a4e61c0b45a1.png)
![image](https://user-images.githubusercontent.com/3498917/48197473-d6db9f00-e37b-11e8-9bb4-338d6714f944.png)

## Acceptance Criteria

- [ ] Settings submenu is accessible
- [ ] Can add/edit platform APIs and dis/connect Facebook.

**Comment by kevinwhoffman** [comment]
@marutim Can you write out the steps to reproduce from a fresh install and indicate which version of WPBR you are using? The video shows two different errors, one in a Facebook class and one in a Google class. Please clarify the steps to recreate. Thanks.

**Comment by marutim** [comment]
@kevinwhoffman I have updated the above with steps to reproduce and visuals. Let me know if you need anything else.

**Comment by kevinwhoffman** [comment]
@marutim I have tested the following:

- Created a fresh install of WP v4.9.8
- Installed WPBR v1.1.0 directly from the website
- Activated WPBR.
- Went to settings page and entered Google API key successfully.
- Also tested entering an invalid Google API key such as `test`.
- All values are saving successfully without the error in your tests.

[The line](https://github.com/impress-org/wp-business-reviews/blob/330e0469e4e68300bf97a70ed7bc05378fd6cf4b/includes/request/class-google-places-request.php#L65) that your error is pointing to suggests that the request is not getting a response from Google and is instead resulting in a WP_Error. You should always get a response from Google, even if the API key is incorrect.

I will add a condition to prevent a fatal error in this circumstance, but I'd also like you to test the request directly in your browser to see what's going on. Replace the `{YOUR_API_KEY_HERE}` with your API key and test this link in your browser.

`https://maps.googleapis.com/maps/api/place/details/json?placeid=ChIJj61dQgK6j4AR4GeTYWZsKWw&key={YOUR_API_KEY_HERE}`

You should get an API response for the Googleplex. If not, let me know what response you do see. Thanks.

**Comment by marutim** [comment]
@kevinwhoffman This seems like it was an issue with my "local by flywheel". After updating the local, everything is working fine. You can close this one.

![image](https://user-images.githubusercontent.com/3498917/48409543-17636000-e762-11e8-95af-172ffb38124c.png)
