### ISSUE TITLE
fix: ensure compatibility with Next Gen Gallery plugin

### ISSUE THREAD

**Issue by marutim** [impress-org/wp-business-reviews#287]
# Bug Report

## User Story

As a user, I would want both WPBR and [Next Gen gallery plugin](https://wordpress.org/plugins/nextgen-gallery/) to play nicely. At the moment the WPBR menu section does not load and the page eventually become unresponsive. This also spikes the browser's CPU usage.

The front end works fine without any issue.
 
## Current Behavior
When Next Gen plugin in activated, one cannot load the WPBR admin menu, the browser keep loading and eventually the notification saying the page is unresponsives pops up.

## Bug Type
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Install and activate Next Gen Gallery plugin a website which has WPBR
2. Once activated, try and access the WPBR sub menus like collections, Single reviews etc. You will find the page keeps loading and become unresponsive

## Related
HS Link: https://secure.helpscout.net/conversation/709269711/29307?folderId=2231395

## Acceptance Criteria

- [x] Can access all the WPBR submenu sections
- [x] Create/edit Collections.
- [x] Create/edit Single Reviews

## Environment

WP version - 4.9.8
WPBR - 1.1.0
Next Gen Gallery - 3.0.16

**Comment by kevinwhoffman** [comment]
@marutim I am not able to reproduce using those plugin versions with the steps provided. I also viewed the customers screencast and I do not see the same endless loading behavior. If you are able to recreate that endless loading, then there should be some indication in Chrome dev tools Console or Network tab that either indicates a JS error or a certain asset that is stuck loading. Please check those tabs and let me know what you see.

**Comment by kevinwhoffman** [comment]
Update: I eventually ran into this bug after leaving NextGen Gallery installed during development. WPBR pages will randomly lock up and the browser tab becomes completely unresponsive. I do not see a spinner like the customer shows, the tab just freezes and does not respond to any clicks.

Like Maruti, I was not able to access the Console or Network tab of dev tools during the freeze. There is also nothing in `debug.log` to explain what is going wrong.

Chrome Version 70.0.3538.102 (Official Build) (64-bit)

**Comment by kevinwhoffman** [comment]
NextGen support recommended commenting out the function that enqueues Font Awesome:

>We have a recent report related to "Font Awesome".
A workaround that the client use what the following:
Commented out the function enqueue_fontawesome in nextgen-gallery/products/photocrati_nextgen/modules/nextgen_gallery_display/module.nextgen_gallery_display.php

This is not an acceptable workaround because the issue will return in the next update of NextGen Gallery.

Instead I have provided this filter to the customer to prevent the single review editor from freezing up:

```php
/**
 * Dequeues NextGEN Gallery's Font Awesome in the single review editor.
 */
function wpbr_dequeue_nextgen_fontawesome() {
	$screen = get_current_screen();

	if ( 'wpbr_review' === $screen->id ) {
		wp_dequeue_script( 'fontawesome_v4_shim' );
		wp_dequeue_script( 'fontawesome' );
		wp_dequeue_style( 'fontawesome_v4_shim_style' );
		wp_dequeue_style( 'fontawesome' );
	}
}

add_action( 'admin_enqueue_scripts', 'wpbr_dequeue_nextgen_fontawesome', 100 );
```

Please notify me of any other reports of this conflict. We may consider adding a compatibility fix to the plugin if it persists.

**Comment by marutim** [comment]
Thanks @kevinwhoffman for the details.
