### ISSUE TITLE
fix: scrolling irregularity in the carousels

### ISSUE THREAD

**Issue by marutim** [impress-org/wp-business-reviews#288]
# Bug Report

## User Story

As a user, I would like to have a seamless experience with the carousel. At the moment the carousel works fine when scrolled using the dots below the carousel but when you try to drag and scroll it behaves irregularly.

For example when you are at the last slot of the carousel ( ie the last dot ) and drag and swipe to the left, it should go to the (n-1) slot but it scroll backs to the second slot or before but not to the (n-1) slot

Check the video from the user to understand this better.

## Current Behavior
Drag and swipe are irregular. Scrolling through dots is fine.

## Expected Behavior

Drag and swipe should be seamless.

## Bug Type

- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Create a collection with carousel set as the presentation format.
2. Scroll to the last slot ( last dot) and then try and drag and swipe left to see the issue.

## Visuals
Video from the user: https://drive.google.com/drive/u/1/folders/1qov7oLD9ol69vmX5pmZ_CWM-ma2WCd6L

## Acceptance Criteria

- [ ] User should be able to scroll back and forth carousels with drag.

## Environment
WPBR 1.2
WP 4.9.8

**Comment by marutim** [comment]
Another user reporting this issue: https://secure.helpscout.net/conversation/758560018/32916/

**Comment by marutim** [comment]
Another HS ticket on this: https://secure.helpscout.net/conversation/761786812/33198?folderId=2120001

**Comment by kevinwhoffman** [comment]
This turned out to be an issue with a string (`"2"`) being passed instead of an integer (`2`) for the number of slides. This happens because values read from the database are always returned as strings. After correcting the type of value, the swiping behavior and pagination bullets now behave as expected.

PR incoming.
