### ISSUE TITLE
fix: facebook recommendations should be fetched and saved correctly.

### ISSUE THREAD

**Issue by marutim** [impress-org/wp-business-reviews#289]
# Bug Report

## User Story

As an admin, I would like to create a collection which displays all  my recent Facebook recommendations correctly.

Now when I try and get reviews, it fetches the Facebook reviews correctly ( combination of recommendations and star ratings ) but when I click the save button it only saves a couple of recommendations correctly

## Current Behavior

It does not save all the recommendations

## Expected Behavior
It should save and display all the recommendations fetched in the first place.

## Bug Type

- [ ] This bug describes functionality that never worked as expected.

## Steps to Reproduce
1. Edit a current Facebook collection or create a new one.
2. Click on get reviews to see all the reviews ( recommendations + ratings ) fetched correctly.
3. Click save to see only a couple recommendations saved.
4. Check the single reviews to see the rest of the recommendations recorded as "unrated".

## Visuals

![1](https://user-images.githubusercontent.com/3498917/48904123-6c4e5700-ee83-11e8-9c39-669aa23623c0.png)
![2](https://user-images.githubusercontent.com/3498917/48904125-6d7f8400-ee83-11e8-8797-e2594a0e26cb.png)
![builder wpbr demo site wordpress](https://user-images.githubusercontent.com/3498917/48904131-6f494780-ee83-11e8-929b-747e926bec88.png)
![single reviews wpbr demo site wordpress](https://user-images.githubusercontent.com/3498917/48904139-72443800-ee83-11e8-8657-c09092ae0ed1.png)

## Related

HS link: https://secure.helpscout.net/conversation/656008881/24731/

## Acceptance Criteria

- [ ] It should save and display all the recommendations fetched in the first place.

## Environment

<details>
   ### WP Business Reviews ###

WPBR Plugin Version: 1.2.0
WPBR Database Version: 1.2.0
Upgraded From: 1.1.0
Active Platforms: Google, Facebook, Yelp, YP
Connected Platforms: Google, Facebook, Yelp
Total Reviews: 94

### WordPress ###

Version: 4.9.8
Language: en_US
Home URL: https://wpbrdemos.com
Site URL: https://wpbrdemos.com
Permalink Structure: /%postname%/
Is this site using HTTPS?: Yes
Can anyone register on this site?: No
Default Comment Status: open
Is this a multisite?: No
User Count: 5
Communication with WordPress.org: WordPress.org is reachable
Create Loopback Requests: The loopback request to your site completed successfully.
Admin AJAX: Accessible

### Server ###

Server Architecture: Linux 3.12.18-clouder0 x86_64
Web Server Software: Apache
PHP Version: 5.6.38 (Supports 64bit values)
PHP SAPI: cgi-fcgi
PHP Max Input Variables: 1000
PHP Time Limit: 120
PHP Memory Limit: 768M
Max Input Time: 120
Upload Max Filesize: 128M
PHP Post Max Size: 128M
cURL Version: 7.59.0 OpenSSL/1.0.2p
SUHOSIN Installed: No
Is the Imagick library available?: No
htaccess rules: Custom rules have been added to your htaccess file
Host Name: m36.siteground.biz

### Active Theme ###

Name: Divi
Version: 3.15 ( Latest version: 3.17.6 )
Author: Elegant Themes
Author Website: http://www.elegantthemes.com
Parent Theme: Not a child theme
Supported Theme Features: custom-background, automatic-feed-links, post-thumbnails, menus, title-tag, post-formats, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, customize-selective-refresh-widgets, editor-style, widgets

### Other Themes (1) ###

Twenty Sixteen (twentysixteen): Version 1.5 by the WordPress team

### Active Plugins (9) ###

BackupBuddy: Version 8.2.8.3 by iThemes
Disable Comments: Version 1.8.0 by Samir Shah
Gravity Forms: Version 2.3.6 by rocketgenius
My Custom Functions: Version 4.31 by Space X-Chimp
Soliloquy: Version 2.5.5.1 by Soliloquy Team
TinyMCE Advanced: Version 4.8.0 by Andrew Ozz
Velvet Blues Update URLs: Version 3.2.8 by VelvetBlues.com
Wordfence Security: Version 7.1.17 by Wordfence
WP Business Reviews: Version 1.2.0 by Impress.org

### Installation Size ###

Uploads Directory: 547.31 MB
Themes Directory: 24.56 MB
Plugins Directory: 51.96 MB
Database Size: 7.45 MB
Whole WordPress Directory: 653.10 MB
Total Installation Size: 660.55 MB

### Database ###

Extension: mysqli
Server Version: 5.6.40-84.0-log
Client Version: 5.5.32
Database Prefix: wp_

### Media Handling ###

Active Editor: WP_Image_Editor_GD
Imagick Module Version: Imagick not available
ImageMagick Version: Imagick not available
GD Version: bundled (2.1.0 compatible)
Ghostscript Version: 9.05

### WordPress Constants ###

ABSPATH: /home/mbymclie/public_html/wpbrdemos.com/
WP_HOME: Undefined
WP_SITEURL: Undefined
WP_DEBUG: Disabled
WP_MAX_MEMORY_LIMIT: 768M
WP_DEBUG_DISPLAY: Enabled
WP_DEBUG_LOG: Disabled
SCRIPT_DEBUG: Disabled
WP_CACHE: Disabled
CONCATENATE_SCRIPTS: Undefined
COMPRESS_SCRIPTS: Undefined
COMPRESS_CSS: Undefined
WP_LOCAL_DEV: Undefined

### Filesystem Permissions ###

Main WordPress Directory: Writable
Content Directory: Writable
Uploads Directory: Writable
Plugins Directory: Writable
Themes Directory: Writable

</details>

**Comment by kevinwhoffman** [comment]
If you had unrated reviews saved prior to the 1.2.0 update, you have to fix those reviews manually in the single reviews editor. New reviews and recommendations going forward should save correctly. Please instruct the customer how to edit the review and change it to a positive recommendation.

My guess is the top 2 recommendations saved correctly because they were not in the database prior to 1.2.0.

**Comment by kevinwhoffman** [comment]
Closing as new reviews after 1.2.0 should be saved correctly, and old `Unrated` reviews can be fixed manually.
