### ISSUE TITLE
fix: prevent media edit link from redirecting to builder

### ISSUE THREAD

**Issue by mathetos** [impress-org/wp-business-reviews#295]
# Bug Report

## User Story

As a WPBR user and site admin, I want to be able to reliably edit my images regardless of how they are uploaded to my media library.

## Current Behavior

Currently, images that are uploaded via WPBR have an edit link which directs me to a page on the WPBR settings area with an error message. The standard WordPress media edit link works as expected however. So this only impacts images that are uploaded via WPBR.

## Expected Behavior

That if WPBR uploads images in any way to my Media Library, that I can edit those images with the WP Core functionality as expected.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [X] I am not sure whether this functionality ever worked as expected.

Most likely this never worked and we just didn't catch it.

## Steps to Reproduce

1. Ensure you have NO images in your Media Library at all first. This is an important step.
1. Upload an image directly to the Media Library.
2. Click on that image for its details, then click on "Edit more details". This should work as intended and show you the intended behavior.
3. Now, go to "Reviews > Single Reviews" and create a new single review and make sure to upload an image to use for the reviewer profile image. 
4. Now navigate to the Media Library and attempt to click on "Edit more details" of that uploaded profile image. When you hover over the "Edit more details" you'll see that the link is different and references the `wpbr-builder` in the url. After the redirect, you should get a Fatal error like this: `Fatal error: Call to a member function init() on a non-object in /app/public/wp-content/plugins/wp-business-reviews/includes/builder/class-builder.php on line 115`
5. Now go back to the original image you uploaded via the Media Library, and see that the edit URL is changed now to the `wpbr-builder` version.

## Visuals

Error message:
![image](https://user-images.githubusercontent.com/930724/51054432-b1dcf580-1591-11e9-8ebf-ce4b8ceeb1c8.png)

See the URL when hovering:
![image](https://user-images.githubusercontent.com/930724/51054470-cb7e3d00-1591-11e9-979c-e468db22ff5b.png)

## Acceptance Criteria

- [ ] When clicking on "Edit more details" link in any and all images produces the desired result.
- [ ] Sites that had that image changed, when they update to the new version of WPBR, their image links are restored to the correct behavior

## Environment

<details>
    ### WP Business Reviews ###

WPBR Plugin Version: 1.2.0
WPBR Database Version: 1.2.0
Upgraded From: 1.2.0
Active Platforms: Google, Facebook
Connected Platforms: Google, Facebook
Total Reviews: 30

### WordPress ###

Version: 5.0.3
Language: en_US
Home URL: https://baytreeevents.test
Site URL: https://baytreeevents.test
Permalink Structure: /%postname%/
Is this site using HTTPS?: Yes
Can anyone register on this site?: No
Default Comment Status: closed
Is this a multisite?: No
User Count: 5
Communication with WordPress.org: WordPress.org is reachable
Create Loopback Requests: The loopback request to your site failed, this may prevent WP_Cron from working, along with theme and plugin editors. Error encountered: (0) cURL error 60: SSL certificate problem: self signed certificate
Admin AJAX: Inaccessible

### Server ###

Server Architecture: Linux 4.9.93-boot2docker x86_64
Web Server Software: nginx/1.10.1
PHP Version: 7.0.3 (Supports 64bit values)
PHP SAPI: fpm-fcgi
PHP Max Input Variables: 3000
PHP Time Limit: 900
PHP Memory Limit: 256M
Max Input Time: -1
Upload Max Filesize: 1000M
PHP Post Max Size: 1000M
cURL Version: 7.38.0 OpenSSL/1.0.1t
SUHOSIN Installed: No
Is the Imagick library available?: Yes
Host Name: 5dd83ce45db6

### Active Theme ###

Name: Customizr Pro
Version: 2.1.15
Author: Press Customizr
Author Website: https://presscustomizr.com/
Parent Theme: Not a child theme
Supported Theme Features: automatic-feed-links, post-formats, custom-logo, post-thumbnails, title-tag, responsive-embeds, customize-selective-refresh-widgets, menus, html5, align-wide, editor-styles, jetpack, bbpress, buddy-press, qtranslate-x, polylang, wpml, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, the-events-calendar, optimize-press, woo-sensei, visual-composer, disqus, uris, tc-unlimited-featured-pages, learnpress, coauthors, yoast-seo-breadcrumbs, widgets, editor-style

### Other Themes (1) ###

Twenty Nineteen (twentynineteen): Version 1.2 by the WordPress team

### Active Plugins (11) ###

Beaver Builder Plugin (Standard Version): Version 2.2.0.4 by The Beaver Builder Team ( Latest version: 2.2.0.4 )
Custom Facebook Feed Pro Personal: Version 3.6.1 by Smash Balloon
Duplicator: Version 1.3.2 by Snap Creek
Facebook Reviews Pro: Version 1.4.2 by RichPlugins <support@richplugins.com>
Redirection: Version 3.6.3 by John Godley
Smush: Version 3.0.2 by WPMU DEV
Updater by BestWebSoft: Version 1.41 by BestWebSoft
UpdraftPlus - Backup/Restore: Version 1.16.0 by UpdraftPlus.Com, DavidAnderson
WP Business Reviews: Version 1.2.0 by Impress.org
Yoast SEO: Version 9.4 by Team Yoast
Yoast SEO: Search index purge: Version 1.1.0 by Team Yoast

### Inactive Plugins (5) ###

Akismet Anti-Spam: Version 4.1 by Automattic
Classic Editor: Version 1.3 by WordPress Contributors
Health Check & Troubleshooting: Version 1.2.3 by The WordPress.org community
Wordfence Security: Version 7.1.20 by Wordfence
WP-Optimize: Version 2.2.10 by David Anderson, Ruhani Rabin, Team Updraft

### Must-Use Plugins (2) ###

Bypass Login: Version 1.1.0 by Stephen Carnam
Health Check Troubleshooting Mode: Version 1.5.0

### Drop-Ins ###

maintenance.php: Custom maintenance message.

### Installation Size ###

Uploads Directory: 4.00 KB
Themes Directory: 34.39 MB
Plugins Directory: 96.95 MB
Database Size: 94.53 MB
Whole WordPress Directory: 304.56 MB
Total Installation Size: 399.09 MB

### Database ###

Extension: mysqli
Server Version: 5.5.60-0+deb8u1
Client Version: mysqlnd 5.0.12-dev - 20150407 - $Id: f59eb767fe17a6679589b5c076d9fa88d3d4eac0 $
Database Prefix: L24aLT4_

### Media Handling ###

Active Editor: WP_Image_Editor_Imagick
Imagick Module Version: 1673
ImageMagick Version: ImageMagick 6.8.9-9 Q16 x86_64 2018-05-18 http://www.imagemagick.org
GD Version: bundled (2.1.0 compatible)
Ghostscript Version: 9.06

### WordPress Constants ###

ABSPATH: /app/public/
WP_HOME: Undefined
WP_SITEURL: Undefined
WP_DEBUG: Disabled
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG_DISPLAY: Enabled
WP_DEBUG_LOG: Disabled
SCRIPT_DEBUG: Disabled
WP_CACHE: Disabled
CONCATENATE_SCRIPTS: Disabled
COMPRESS_SCRIPTS: Undefined
COMPRESS_CSS: Undefined
WP_LOCAL_DEV: Undefined

### Filesystem Permissions ###

Main WordPress Directory: Writable
Content Directory: Writable
Uploads Directory: Writable
Plugins Directory: Writable
Themes Directory: Writable
Must-Use Plugins Directory: Writable

</details>

**Comment by kevinwhoffman** [comment]
This has been fixed in https://github.com/impress-org/wp-business-reviews/commit/e400ef43eb85933aeffa169f99f093c5100e079c.

Explanation: We have to filter the post edit links in the Collections list table in order to redirect to the builder. Usually a screen object is available to test against, however when an image is viewed from the media library in a modal window, there is no screen object. This was causing the filter to be applied on the wrong screen, in this case the media library. I have updated the condition to return the original link should there be any other cases in which a screen object is not available.
