### ISSUE TITLE
fix: ensure Facebook reviewer images display

### ISSUE THREAD

**Issue by kevinwhoffman** [impress-org/wp-business-reviews#297]
# Bug Report

## User Story

As a user, I want my Facebook reviewer images to display so that there are no awkward empty white spaces in my reviews.

## Previous Behavior

Previously, the `ratings` endpoint provided the reviewer's Facebook user ID in the API response. This user ID was then used to generate an image like so:

`https://graph.facebook.com/{$user_id}/picture?width=120&height=120`

## New Behavior

Due to a recent change in the Facebook API response, the reviewer's Facebook user ID is no longer returned. Instead, the reviewer ID that is now available is referred to as a Page-Scoped ID. It is a unique user ID that is only relevant to the Page on which the review was left. It is NOT the same as the Facebook user's ID.

In order to get an image using the page-scoped ID, we must pass the page access token.

`https://graph.facebook.com/{$user_id}/picture?width=120&height=120&access_token={$page_access_token}`

## Bug Type

- [x] This bug describes functionality that once worked as expected in version 1.2.0.
- [ ] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Connect to Facebook.
2. Create a new collection and get reviews.
3. Note the missing reviewer images.

## Visuals

![image](https://user-images.githubusercontent.com/1938671/51587390-a9988a80-1eae-11e9-9b9f-197bbfd57927.png)

## Possible Solution

- Update the way in which the reviewer image URL is currently generated.
- Add a cron job to refresh the reviewer images so they do not expire like they did in #261.

## Related

#261

## Acceptance Criteria

- [x] New Facebook collections show reviewer images.
- [x] Existing Facebook collections created in v1.2.0 still show reviewer images.

**Comment by kevinwhoffman** [comment]
## Status Update

Today I implemented `wp_handle_sideload()` to save images locally. Through the use of the `upload_dir` filter, these images are saved to a custom directory `uploads/wp-business-reviews/facebook`.

These images are not visible in the Media Library. They are treated the same as remote image URLs from Google or Yelp but happen to be stored locally. The benefit is that there will be no concern over API changes or expired URLs in the future as it relates to Facebook.

## Next Steps

1. Save the URL of the local image to the same post meta field that normally holds the remote URL.
2. Ensure that deleting a review also deletes the image from `uploads/wp-business-reviews/facebook`.
3. Ensure that uninstalling the plugin with setting to remove data also deletes this directory.

**Comment by marutim** [comment]
Another ticket on this today: https://secure.helpscout.net/conversation/770763011/33838/

**Comment by kevinwhoffman** [comment]
## Status Update

I pushed the work done so far in this `feat/sideload-fb-images` but I'm not sure this is the best path forward due to the results and what I learned in the process.

It is currently taking about 10 seconds for a collection of 24 reviews to be retrieved and have their images sideloaded. This wait time could be shifted to occur during `Save` instead of on `Get Reviews` but the wait time is there regardless. It's just a slow operation to fetch and save that many images while the user waits.

Even if we decide we're okay with this delay, there are still several tasks necessary to update existing images and hook in to delete them when appropriate.

### Next Steps

At this point, I think it is worth trying the approach of refreshing images periodically via WP Cron. I looked into the ingredients necessary and we already have the info we need in the database. I'd like to take a few hours to pursue the Cron approach which would have the following benefits:

- No additional wait time when getting or saving reviews.
- No additional hooks necessary to delete local images upon post delete or uninstall.
- Facebook reviews would retain a consistent structure with the other platforms.
- Facebook reviews would reflect profile picture changes.
- Less future maintenance related to local images.

**Comment by kevinwhoffman** [comment]
## Status Update

### Fixing New Images

New image URLs are now working using the URL of the user picture from the rating response. This URL will eventually expire and need refreshed.

### Fixing Old Images and Refreshing Images Over Time

I found that using `wp_remote_get()` will provide access to the redirected URL which points to the JPG image.

```php
$response = wp_remote_get( 'https://graph.facebook.com/USER_ID/picture?width=120&height=120&access_token=PAGE_ACCESS_TOKEN' );
$url = $response['http_response']->get_response_object()->url; // URL of the reviewer image for use in front end
```

This is good news because it doesn't require fetching each individual review just to get the image URL.

### Next Steps

1. Write an upgrade routine to convert old image URLs to new image URLs.
2. Write cron job using the same logic and schedule to occur on weekly basis.

**Comment by kevinwhoffman** [comment]
## Status Update

Today I completed the following:

- Updated the URL format for all Facebook reviewer images going forward.
- Added a `Facebook_Review_Refresher` class to handle updating reviews over time.
- Added an upgrade routine using the `Facebook_Review_Refresher` to convert existing URLs to the new format.

### Next Steps

1. Add cron job that leverages the `Facebook_Review_Refresher` to refresh image URLs for any reviews that have not been refreshed in the last week.
2. Test the upgrade from 1.0.0 - 1.2.0 installs to 1.2.1 and ensure the cron is set on update.
